### ISSUE TITLE
Windows 7 doesn’t resolve hostname `0.0.0.0`

### ISSUE THREAD

**Issue by yuens1002** [sbruchmann/brackets-static-preview#12]
hi there, all i get is the webpage is not available when i fire up static preview.... tried changing the default port and ip, but not working either.  i'm sure it's something to do on my end. but i  haven't been able to figure out.  the machine is running on win7 64bit.  

![image](https://cloud.githubusercontent.com/assets/6596603/3382999/9b3ea9fc-fc43-11e3-9eae-c3c98c78fbd0.png)

**Comment by htmlstrap** [comment]
Hi there!
My Static Preview doesn't even start for some reason as it used to. Need help!!!!
Thanks a lot!

**Comment by sbruchmann** [comment]
Hi @htmlstrap,

are there any errors relating to this extension in the developer tools?

**Comment by htmlstrap** [comment]
well, I re-installed the editor and all the extensions. so, now it work well.... thanks!
